import { Router } from "express";
import adminLoginRouter from "./admin/index.js";
import memberLoginRouter from "./member/index.js";
import constituencyRouter from "./constituency/constituency.js";
import pollingStationRouter from "./constituency/pollingStation.js";
import eventRouter from "./events/events.js";
import newsRouter from "./news/news.js";
import newsCommentRouter from "./news/newsComment.js";
import socialActivityRouter from "./socialActivity/socialActivity.js";
import socialActivityCommentRouter from "./socialActivity/socialActivityComment.js";
const allRouter = Router();
allRouter.use("/admin", adminLoginRouter);
allRouter.use("/member", memberLoginRouter);
allRouter.use("/constituency", constituencyRouter);
allRouter.use("/pollingstation", pollingStationRouter);
allRouter.use("/event", eventRouter);
allRouter.use("/news", newsRouter);
allRouter.use("/comment", newsCommentRouter);
allRouter.use("/socialactivity", socialActivityRouter);
allRouter.use("/socialactivitycomment", socialActivityCommentRouter);
export default allRouter;
